name: hexlet-check

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Hexlet project check
        uses: hexlet/project-action@release

      - name: npm install, build
        run: make install
